
export const FETCH_COUNTRIES_CASES = "FETCH_COUNTRIES_CASES";

export const FETCH_WORLD_TOTAL = "FETCH_WORLD_TOTAL";

export const FETCH_CURRENT_PAGE = "FETCH_CURRENT_PAGE";

export const HTTP_ERROR = "HTTP_ERROR";

export const FETCH_COUNTRY_HISTORY = "FETCH_COUNTRY_HISTORY";

export const FETCH_FOLLOWED_COUNTRIES = "FETCH_FOLLOWED_COUNTRIES";

export const FOLLOW_COUNTRY = "FOLLOW_COUNTRY";

export const UNFOLLOW_COUNTRY ="UNFOLLOW_COUNTRY";

export const SEARCH_COUNTRY ="SEARCH_COUNTRY";

export const LOADING_PAGE ="LOADING_PAGE";
 